name: Generate Stats Images

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  UV_COMPILE_BYTECODE: 1
  python-version: "3.13"
  working-directory: github_stats  # name of the dir in the repo
  output-dir: generated            # name of the dir the images are written out to
  output-branch: github_stats_output  # name of the dir in the repo

defaults:
  run:
    shell: bash

jobs:
  githubstats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.python-version }}
          cache-dependency-glob: ${{ env.working-directory }}/*.py

      - name: Run
        working-directory: ${{ env.working-directory }}
        run: uv run generate_images.py
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXCLUDED: ${{ secrets.EXCLUDED }}
          EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
          COUNT_STATS_FROM_FORKS: ${{ secrets.COUNT_STATS_FROM_FORKS }}
    
      - name: Commit
        run: |
          git config --global user.name "github-stats[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m 'temp commit' || echo
          git checkout $output-branch 2>/dev/null || git checkout --orphan $output-branch && git rm -rf . && git checkout main -- $working-directory/$vars.output-dir
          git commit -m 'Update generated files' || echo
          git push origin $output-branch -f
